version: '3.5'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      - DB_SERVER_HOST=localhost  # Referência ao MySQL
      - MYSQL_DATABASE=zabbix                 # Nome do banco de dados do zabbix
      - MYSQL_USER=zabbix                     # Usuário do banco de dados
      - MYSQL_PASSWORD=BHU*nji9      # Senha do usuário do banco de dados
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
    depends_on:
      - zabbix-web

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=localhost   # Nome do banco de dados do zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=sua_senha_segura
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ=America/Recife              # Ajuste o timezone para sua região
    ports:
      - "8080:8080"
    networks:
      - zabbix-net
networks:
  zabbix-net:
    driver: bridge
